### ISSUE TITLE
Remove usage of `int` method within SQLite interface TimestampType

### ISSUE THREAD

**Issue by jaridmargolin** [Jaymon/prom#100]
`int(...)` is used several times within the [convert](https://github.com/Jaymon/prom/blob/master/prom/interface/sqlite.py#L86) method of `TimestampType`. This, however, leads to the unintended consequence of trimming off leading 0s from any string segment. All usages of `int(...)` should be replaced with alternative solutions.

**Comment by Jaymon** [comment]
By way of example, notice the milliseconds in the original (057350) and the converted (573500)

```
'original': '2020-03-25T19:34:05.057350Z
'converted': datetime.datetime(2020, 3, 25, 19, 34, 5, 573500)
```

**Comment by Jaymon** [comment]
This was the only discussion I could find even remotely about this problem: python: [subtraction of timestamps fails due to omitted leading zeros in microsec](https://stackoverflow.com/questions/44048842/python-subtraction-of-timestamps-fails-due-to-omitted-leading-zeros-in-microsec)

And it lead me to the discovery that the [timedelta class](https://docs.python.org/3/library/datetime.html#datetime.timedelta) has a milliseconds argument I could use, which allowed me to break up the microseconds into two chunks of 3 and then add them to the timestamp to keep the correct value from the parsed string datetime.

search:

* python datetime leading zeros microseconds
* python datetime leading zeros microseconds site:stackoverflow.com
* values of right of decimal
* python datetime microseconds with leading zeros
